### ISSUE TITLE
SPI support

### ISSUE THREAD

**Issue by jmhjimenez** [adafruit/Adafruit_CircuitPython_ADXL34x#28]
Hello! Is it possible with this library to use SPI connection instead of I2C? I'm planning to use 3200Hz as my data rate, but it says in the datasheet that 800Hz ODR is the limit of I2C connection due to its speed.

**Comment by ladyada** [comment]
nope - this library does not have SPI support. there is no plan or eta to add it!

**Comment by jposada202020** [comment]
Closing for now. Thanks
