### ISSUE TITLE
tap, double-tap, activity, freefall

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_ADXL34x#3]
lets add these built in hardware features!

**Comment by siddacious** [comment]
As I mentioned to kattni I'll be returning from a con on the 19th so I can get started on this after that. This should be fun!

**Comment by siddacious** [comment]
@microbuilder, @kattni mentioned that you mentioned that you might be looking at this so I wanted to check with you before I started on it. If you've done some work on this already, otherwise I'm ready to start on this.

Thanks!
-sBs

**Comment by ladyada** [comment]
i dont think we've done anything with it so go ahead!

**Comment by siddacious** [comment]
All done!
