### ISSUE TITLE
i cant see gyro parameter

### ISSUE THREAD

**Issue by ufukasia** [adafruit/Adafruit_CircuitPython_ADXL34x#39]
hello everyone I want to use accelerometer data from adxl345
but accelerometer data have noise already you now so I need extra gyro data for fusion (complementary filter)
then, came to mind this  "accelerometer = adafruit_adxl34x.ADXL345(i2c)"  output,  is it include any filter ?

**Comment by caternuson** [comment]
It does not include any filtering other than what the is built into the ADXL34x sensor itself (if any). The datasheet would have the details about this.
