### ISSUE TITLE
how to set  data_rate

### ISSUE THREAD

**Issue by pandjer** [adafruit/Adafruit_CircuitPython_ADXL34x#40]
Hello everyone. I dont know how to change the data rate. I have the register address "_REG_BW_RATE" and the desired data rate "datarate.RATE_800_HZ" to change the data rate. Now I have done "accelerometer._write_register_byte(_REG_BW_RATE, datarate.RATE_800_HZ)" but no change. What did I do wrong? (p.s.  I use ADXL375)

**Comment by tannewt** [comment]
There is a separate library for the ADXL375 here: https://github.com/adafruit/Adafruit_CircuitPython_ADXL37x
