### ISSUE TITLE
Fix buffer size used by struct.unpack for CPython compatability

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_ADXL34x#6]
https://forums.adafruit.com/viewtopic.php?f=60&t=145928

related, for fwiw:
https://github.com/adafruit/Adafruit_CircuitPython_MAX31856/issues/4

**Comment by ladyada** [comment]
oi, not surprsing, we haven't tested this on linux yet

**Comment by siddacious** [comment]
Methinks I need a RPi :|

**Comment by siddacious** [comment]
Released a fix and the user reported it working
